# Generated by Django 5.1.6 on 2025-02-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('patient', 'doctor')},
        ),
    ]
