# Generated by Django 5.1.6 on 2025-02-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_specialty_name_specialty_specialty_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
