# Generated by Django 5.1.6 on 2025-02-19 13:19

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_rename_records_record_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ПН', 'ПН'), ('ВТ', 'ВТ'), ('СР', 'СР'), ('ЧТ', 'ЧТ'), ('ПТ', 'ПТ'), ('СБ', 'СБ')], max_length=18),
        ),
    ]
