# Generated by Django 5.1.6 on 2025-02-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_doctor_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('planned', 'planned'), ('at appointment', 'at appointment'), ('completed', 'completed')], default='planned', max_length=16),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='department_doctors', to='hospital.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(related_name='specialty_doctors', to='hospital.specialty'),
        ),
    ]
