# Generated by Django 5.1.6 on 2025-02-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_alter_doctor_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_doctors', to='hospital.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(blank=True, null=True, related_name='specialty_doctors', to='hospital.specialty'),
        ),
    ]
