# Generated by Django 5.1.6 on 2025-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_alter_doctor_department_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('III+', 'III+')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('mail', 'mail'), ('female', 'female')], max_length=8, null=True),
        ),
    ]
