# Generated by Django 5.1.6 on 2025-02-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_patient_blood_group_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(related_name='specialty_doctors', to='hospital.specialty'),
        ),
    ]
