# Generated by Django 5.1.6 on 2025-02-21 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='patient',
        ),
        migrations.AddField(
            model_name='chat',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='chat',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.patient'),
        ),
    ]
